/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppDashboardIndexRouteImport } from './routes/app.dashboard.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppDashboardSafeLocationsRouteImport } from './routes/app.dashboard.safe-locations'
import { Route as AppDashboardProfileRouteImport } from './routes/app.dashboard.profile'
import { Route as AppDashboardPollutionRouteImport } from './routes/app.dashboard.pollution'
import { Route as AppDashboardFeedbackRouteImport } from './routes/app.dashboard.feedback'
import { Route as AppDashboardAlertsRouteImport } from './routes/app.dashboard.alerts'
import { Route as AppDashboardAirIndiaRouteImport } from './routes/app.dashboard.air-india'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminPollutionRouteImport } from './routes/app.admin.pollution'
import { Route as AppAdminAnalyticsRouteImport } from './routes/app.admin.analytics'
import { Route as AppAdminAlertsRouteImport } from './routes/app.admin.alerts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppDashboardSafeLocationsRoute =
  AppDashboardSafeLocationsRouteImport.update({
    id: '/safe-locations',
    path: '/safe-locations',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardProfileRoute = AppDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardPollutionRoute = AppDashboardPollutionRouteImport.update({
  id: '/pollution',
  path: '/pollution',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardFeedbackRoute = AppDashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAlertsRoute = AppDashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAirIndiaRoute = AppDashboardAirIndiaRouteImport.update({
  id: '/air-india',
  path: '/air-india',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPollutionRoute = AppAdminPollutionRouteImport.update({
  id: '/pollution',
  path: '/pollution',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlertsRoute = AppAdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/alerts': typeof AppAdminAlertsRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/pollution': typeof AppAdminPollutionRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/dashboard/air-india': typeof AppDashboardAirIndiaRoute
  '/app/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/app/dashboard/feedback': typeof AppDashboardFeedbackRoute
  '/app/dashboard/pollution': typeof AppDashboardPollutionRoute
  '/app/dashboard/profile': typeof AppDashboardProfileRoute
  '/app/dashboard/safe-locations': typeof AppDashboardSafeLocationsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppIndexRoute
  '/app/admin/alerts': typeof AppAdminAlertsRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/pollution': typeof AppAdminPollutionRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/dashboard/air-india': typeof AppDashboardAirIndiaRoute
  '/app/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/app/dashboard/feedback': typeof AppDashboardFeedbackRoute
  '/app/dashboard/pollution': typeof AppDashboardPollutionRoute
  '/app/dashboard/profile': typeof AppDashboardProfileRoute
  '/app/dashboard/safe-locations': typeof AppDashboardSafeLocationsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/alerts': typeof AppAdminAlertsRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/pollution': typeof AppAdminPollutionRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/dashboard/air-india': typeof AppDashboardAirIndiaRoute
  '/app/dashboard/alerts': typeof AppDashboardAlertsRoute
  '/app/dashboard/feedback': typeof AppDashboardFeedbackRoute
  '/app/dashboard/pollution': typeof AppDashboardPollutionRoute
  '/app/dashboard/profile': typeof AppDashboardProfileRoute
  '/app/dashboard/safe-locations': typeof AppDashboardSafeLocationsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/'
    | '/app/admin/alerts'
    | '/app/admin/analytics'
    | '/app/admin/pollution'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/dashboard/air-india'
    | '/app/dashboard/alerts'
    | '/app/dashboard/feedback'
    | '/app/dashboard/pollution'
    | '/app/dashboard/profile'
    | '/app/dashboard/safe-locations'
    | '/app/admin/'
    | '/app/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/app'
    | '/app/admin/alerts'
    | '/app/admin/analytics'
    | '/app/admin/pollution'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/dashboard/air-india'
    | '/app/dashboard/alerts'
    | '/app/dashboard/feedback'
    | '/app/dashboard/pollution'
    | '/app/dashboard/profile'
    | '/app/dashboard/safe-locations'
    | '/app/admin'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/'
    | '/app/admin/alerts'
    | '/app/admin/analytics'
    | '/app/admin/pollution'
    | '/app/admin/reports'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/dashboard/air-india'
    | '/app/dashboard/alerts'
    | '/app/dashboard/feedback'
    | '/app/dashboard/pollution'
    | '/app/dashboard/profile'
    | '/app/dashboard/safe-locations'
    | '/app/admin/'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/dashboard/safe-locations': {
      id: '/app/dashboard/safe-locations'
      path: '/safe-locations'
      fullPath: '/app/dashboard/safe-locations'
      preLoaderRoute: typeof AppDashboardSafeLocationsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/profile': {
      id: '/app/dashboard/profile'
      path: '/profile'
      fullPath: '/app/dashboard/profile'
      preLoaderRoute: typeof AppDashboardProfileRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/pollution': {
      id: '/app/dashboard/pollution'
      path: '/pollution'
      fullPath: '/app/dashboard/pollution'
      preLoaderRoute: typeof AppDashboardPollutionRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/feedback': {
      id: '/app/dashboard/feedback'
      path: '/feedback'
      fullPath: '/app/dashboard/feedback'
      preLoaderRoute: typeof AppDashboardFeedbackRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/alerts': {
      id: '/app/dashboard/alerts'
      path: '/alerts'
      fullPath: '/app/dashboard/alerts'
      preLoaderRoute: typeof AppDashboardAlertsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/air-india': {
      id: '/app/dashboard/air-india'
      path: '/air-india'
      fullPath: '/app/dashboard/air-india'
      preLoaderRoute: typeof AppDashboardAirIndiaRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pollution': {
      id: '/app/admin/pollution'
      path: '/pollution'
      fullPath: '/app/admin/pollution'
      preLoaderRoute: typeof AppAdminPollutionRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/analytics': {
      id: '/app/admin/analytics'
      path: '/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/alerts': {
      id: '/app/admin/alerts'
      path: '/alerts'
      fullPath: '/app/admin/alerts'
      preLoaderRoute: typeof AppAdminAlertsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAlertsRoute: typeof AppAdminAlertsRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminPollutionRoute: typeof AppAdminPollutionRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAlertsRoute: AppAdminAlertsRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminPollutionRoute: AppAdminPollutionRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDashboardRouteChildren {
  AppDashboardAirIndiaRoute: typeof AppDashboardAirIndiaRoute
  AppDashboardAlertsRoute: typeof AppDashboardAlertsRoute
  AppDashboardFeedbackRoute: typeof AppDashboardFeedbackRoute
  AppDashboardPollutionRoute: typeof AppDashboardPollutionRoute
  AppDashboardProfileRoute: typeof AppDashboardProfileRoute
  AppDashboardSafeLocationsRoute: typeof AppDashboardSafeLocationsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAirIndiaRoute: AppDashboardAirIndiaRoute,
  AppDashboardAlertsRoute: AppDashboardAlertsRoute,
  AppDashboardFeedbackRoute: AppDashboardFeedbackRoute,
  AppDashboardPollutionRoute: AppDashboardPollutionRoute,
  AppDashboardProfileRoute: AppDashboardProfileRoute,
  AppDashboardSafeLocationsRoute: AppDashboardSafeLocationsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
